INSERT INTO teams (league_id, slug, name, short_name, abbreviation)
SELECT l.id, team.slug, team.name, team.short_name, team.abbreviation
FROM leagues l
JOIN (
  VALUES
    ('premier-league', 'brighton-hove-albion', 'Brighton & Hove Albion', 'Brighton', 'BHA'),
    ('premier-league', 'burnley', 'Burnley', 'Burnley', 'BUR'),
    ('premier-league', 'wolverhampton-wanderers', 'Wolverhampton Wanderers', 'Wolves', 'WOL'),
    ('premier-league', 'crystal-palace', 'Crystal Palace', 'Crystal Palace', 'CRY'),
    ('premier-league', 'fulham', 'Fulham', 'Fulham', 'FUL'),
    ('premier-league', 'brentford', 'Brentford', 'Brentford', 'BRE'),
    ('premier-league', 'nottingham-forest', 'Nottingham Forest', 'Nottm Forest', 'NFO'),
    ('premier-league', 'afc-bournemouth', 'AFC Bournemouth', 'Bournemouth', 'BOU'),
    ('premier-league', 'sunderland', 'Sunderland', 'Sunderland', 'SUN'),
    ('premier-league', 'everton', 'Everton', 'Everton', 'EVE'),
    ('premier-league', 'west-ham-united', 'West Ham United', 'West Ham', 'WHU'),
    ('premier-league', 'leeds-united', 'Leeds United', 'Leeds', 'LEE'),
    ('serie-a', 'fiorentina', 'Fiorentina', 'Fiorentina', 'FIO'),
    ('serie-a', 'sassuolo', 'Sassuolo', 'Sassuolo', 'SAS'),
    ('serie-a', 'bologna', 'Bologna', 'Bologna', 'BOL'),
    ('serie-a', 'frosinone', 'Frosinone', 'Frosinone', 'FRO'),
    ('serie-a', 'genoa', 'Genoa', 'Genoa', 'GEN'),
    ('serie-a', 'monza', 'Monza', 'Monza', 'MON'),
    ('serie-a', 'parma', 'Parma', 'Parma', 'PAR'),
    ('serie-a', 'cagliari', 'Cagliari', 'Cagliari', 'CAG'),
    ('serie-a', 'torino', 'Torino', 'Torino', 'TOR'),
    ('serie-a', 'udinese', 'Udinese', 'Udinese', 'UDI'),
    ('serie-a', 'como', 'Como', 'Como', 'COM'),
    ('serie-a', 'venezia', 'Venezia', 'Venezia', 'VEN'),
    ('serie-a', 'lecce', 'Lecce', 'Lecce', 'LEC'),
    ('bundesliga', 'heidenheim', '1. FC Heidenheim 1846', 'Heidenheim', 'HDH'),
    ('bundesliga', 'mainz', 'Mainz', 'Mainz', 'M05'),
    ('bundesliga', 'union-berlin', '1. FC Union Berlin', 'Union Berlin', 'FCU'),
    ('bundesliga', 'augsburg', 'FC Augsburg', 'Augsburg', 'FCA'),
    ('bundesliga', 'hamburg-sv', 'Hamburg SV', 'Hamburg', 'HSV'),
    ('bundesliga', 'fc-cologne', 'FC Cologne', 'Cologne', 'KOE'),
    ('bundesliga', 'borussia-monchengladbach', 'Borussia Monchengladbach', 'Gladbach', 'BMG'),
    ('bundesliga', 'hoffenheim', 'TSG Hoffenheim', 'Hoffenheim', 'TSG'),
    ('bundesliga', 'vfb-stuttgart', 'VfB Stuttgart', 'Stuttgart', 'VFB'),
    ('bundesliga', 'sc-freiburg', 'SC Freiburg', 'Freiburg', 'SCF'),
    ('bundesliga', 'st-pauli', 'St. Pauli', 'St. Pauli', 'STP'),
    ('bundesliga', 'wolfsburg', 'VfL Wolfsburg', 'Wolfsburg', 'WOB'),
    ('bundesliga', 'werder-bremen', 'Werder Bremen', 'Bremen', 'SVW'),
    ('ligue-1', 'brest', 'Brest', 'Brest', 'BRE'),
    ('ligue-1', 'angers', 'Angers', 'Angers', 'ANG'),
    ('ligue-1', 'auxerre', 'AJ Auxerre', 'Auxerre', 'AJA'),
    ('ligue-1', 'lorient', 'Lorient', 'Lorient', 'FCL'),
    ('ligue-1', 'le-havre', 'Le Havre AC', 'Le Havre', 'HAC'),
    ('ligue-1', 'lens', 'Lens', 'Lens', 'RCL'),
    ('ligue-1', 'rennes', 'Stade Rennais', 'Rennes', 'REN'),
    ('ligue-1', 'nantes', 'Nantes', 'Nantes', 'NAN'),
    ('ligue-1', 'toulouse', 'Toulouse', 'Toulouse', 'TFC'),
    ('ligue-1', 'nice', 'Nice', 'Nice', 'NIC'),
    ('ligue-1', 'metz', 'Metz', 'Metz', 'MET'),
    ('ligue-1', 'paris-fc', 'Paris FC', 'Paris FC', 'PFC'),
    ('ligue-1', 'strasbourg', 'Strasbourg', 'Strasbourg', 'STR'),
    ('uefa-champions-league', 'ucl-paris-saint-germain', 'Paris Saint-Germain', 'PSG', 'PSG'),
    ('uefa-champions-league', 'ucl-arsenal', 'Arsenal', 'Arsenal', 'ARS')
) AS team(league_slug, slug, name, short_name, abbreviation) ON team.league_slug = l.slug
ON CONFLICT (slug) DO NOTHING;

INSERT INTO source_team_aliases (source_id, team_id, alias, normalized_alias)
SELECT ds.id, t.id, alias.alias, alias.normalized_alias
FROM data_sources ds
JOIN (
  VALUES
    ('espn-premier-league', 'brighton-hove-albion', 'Brighton & Hove Albion', 'brighton hove albion'),
    ('espn-premier-league', 'burnley', 'Burnley', 'burnley'),
    ('espn-premier-league', 'wolverhampton-wanderers', 'Wolverhampton Wanderers', 'wolverhampton wanderers'),
    ('espn-premier-league', 'wolverhampton-wanderers', 'Wolves', 'wolves'),
    ('espn-premier-league', 'crystal-palace', 'Crystal Palace', 'crystal palace'),
    ('espn-premier-league', 'fulham', 'Fulham', 'fulham'),
    ('espn-premier-league', 'brentford', 'Brentford', 'brentford'),
    ('espn-premier-league', 'nottingham-forest', 'Nottingham Forest', 'nottingham forest'),
    ('espn-premier-league', 'afc-bournemouth', 'AFC Bournemouth', 'afc bournemouth'),
    ('espn-premier-league', 'afc-bournemouth', 'Bournemouth', 'bournemouth'),
    ('espn-premier-league', 'sunderland', 'Sunderland', 'sunderland'),
    ('espn-premier-league', 'everton', 'Everton', 'everton'),
    ('espn-premier-league', 'west-ham-united', 'West Ham United', 'west ham united'),
    ('espn-premier-league', 'west-ham-united', 'West Ham', 'west ham'),
    ('espn-premier-league', 'leeds-united', 'Leeds United', 'leeds united'),
    ('espn-serie-a', 'roma', 'AS Roma', 'as roma'),
    ('espn-serie-a', 'fiorentina', 'Fiorentina', 'fiorentina'),
    ('espn-serie-a', 'sassuolo', 'Sassuolo', 'sassuolo'),
    ('espn-serie-a', 'bologna', 'Bolonia', 'bolonia'),
    ('espn-serie-a', 'bologna', 'Bologna', 'bologna'),
    ('espn-serie-a', 'frosinone', 'Frosinone', 'frosinone'),
    ('espn-serie-a', 'genoa', 'Genova', 'genova'),
    ('espn-serie-a', 'genoa', 'Genoa', 'genoa'),
    ('espn-serie-a', 'monza', 'Monza', 'monza'),
    ('espn-serie-a', 'parma', 'Parma', 'parma'),
    ('espn-serie-a', 'cagliari', 'Cagliari', 'cagliari'),
    ('espn-serie-a', 'torino', 'Torino', 'torino'),
    ('espn-serie-a', 'udinese', 'Udinese', 'udinese'),
    ('espn-serie-a', 'como', 'Como', 'como'),
    ('espn-serie-a', 'venezia', 'Venezia', 'venezia'),
    ('espn-serie-a', 'lecce', 'Lecce', 'lecce'),
    ('espn-bundesliga', 'heidenheim', '1. FC Heidenheim 1846', '1 fc heidenheim 1846'),
    ('espn-bundesliga', 'heidenheim', 'Heidenheim', 'heidenheim'),
    ('espn-bundesliga', 'mainz', 'Mainz', 'mainz'),
    ('espn-bundesliga', 'union-berlin', '1. FC Union Berlin', '1 fc union berlin'),
    ('espn-bundesliga', 'union-berlin', 'Union Berlin', 'union berlin'),
    ('espn-bundesliga', 'augsburg', 'FC Augsburg', 'fc augsburg'),
    ('espn-bundesliga', 'augsburg', 'Augsburg', 'augsburg'),
    ('espn-bundesliga', 'hamburg-sv', 'Hamburg SV', 'hamburg sv'),
    ('espn-bundesliga', 'fc-cologne', 'FC Cologne', 'fc cologne'),
    ('espn-bundesliga', 'fc-cologne', 'Cologne', 'cologne'),
    ('espn-bundesliga', 'borussia-monchengladbach', 'Borussia Monchengladbach', 'borussia monchengladbach'),
    ('espn-bundesliga', 'borussia-monchengladbach', 'Borussia Monchengladbach', 'borussia monchengladbach'),
    ('espn-bundesliga', 'hoffenheim', 'TSG Hoffenheim', 'tsg hoffenheim'),
    ('espn-bundesliga', 'vfb-stuttgart', 'VfB Stuttgart', 'vfb stuttgart'),
    ('espn-bundesliga', 'sc-freiburg', 'SC Freiburg', 'sc freiburg'),
    ('espn-bundesliga', 'st-pauli', 'St. Pauli', 'st pauli'),
    ('espn-bundesliga', 'wolfsburg', 'VfL Wolfsburg', 'vfl wolfsburg'),
    ('espn-bundesliga', 'werder-bremen', 'Werder Bremen', 'werder bremen'),
    ('espn-ligue-1', 'brest', 'Brest', 'brest'),
    ('espn-ligue-1', 'angers', 'Angers', 'angers'),
    ('espn-ligue-1', 'auxerre', 'AJ Auxerre', 'aj auxerre'),
    ('espn-ligue-1', 'auxerre', 'Auxerre', 'auxerre'),
    ('espn-ligue-1', 'lorient', 'Lorient', 'lorient'),
    ('espn-ligue-1', 'le-havre', 'Le Havre AC', 'le havre ac'),
    ('espn-ligue-1', 'le-havre', 'Le Havre', 'le havre'),
    ('espn-ligue-1', 'lens', 'Lens', 'lens'),
    ('espn-ligue-1', 'rennes', 'Stade Rennais', 'stade rennais'),
    ('espn-ligue-1', 'rennes', 'Rennes', 'rennes'),
    ('espn-ligue-1', 'nantes', 'Nantes', 'nantes'),
    ('espn-ligue-1', 'toulouse', 'Toulouse', 'toulouse'),
    ('espn-ligue-1', 'nice', 'Nice', 'nice'),
    ('espn-ligue-1', 'metz', 'Metz', 'metz'),
    ('espn-ligue-1', 'paris-fc', 'Paris FC', 'paris fc'),
    ('espn-ligue-1', 'strasbourg', 'Strasbourg', 'strasbourg'),
    ('espn-ligue-1', 'monaco', 'AS Monaco', 'as monaco'),
    ('espn-ligue-1', 'paris-saint-germain', 'Paris Saint-Germain', 'paris saint germain'),
    ('espn-uefa-champions-league', 'ucl-paris-saint-germain', 'Paris Saint-Germain', 'paris saint germain'),
    ('espn-uefa-champions-league', 'ucl-paris-saint-germain', 'PSG', 'psg'),
    ('espn-uefa-champions-league', 'ucl-arsenal', 'Arsenal', 'arsenal')
) AS alias(source_slug, team_slug, alias, normalized_alias) ON alias.source_slug = ds.slug
JOIN teams t ON t.slug = alias.team_slug
ON CONFLICT (source_id, normalized_alias) DO NOTHING;
