INSERT INTO football_competition_registry (
  league_id,
  canonical_name,
  display_name,
  confederation,
  region,
  country,
  competition_type,
  tier,
  trust_status,
  trust_score,
  priority_score,
  enabled,
  markets_enabled,
  provider_mappings,
  aliases,
  is_domestic,
  is_continental,
  is_global,
  is_friendly,
  manual_only,
  notes
)
VALUES (
  'england-league-cup',
  'EFL League Cup',
  'EFL League Cup',
  'UEFA',
  'Europe',
  'England',
  'domestic_cup',
  'WATCH',
  'WATCH',
  74,
  74,
  true,
  '{"moneyline_3way": true, "draw_no_bet": true, "double_chance": true, "total_goals_2_5": true, "btts": false}'::jsonb,
  '{"espn": "eng.league_cup", "manual": "england-league-cup"}'::jsonb,
  '["League Cup", "EFL Cup", "EFL League Cup", "Carabao Cup", "England League Cup"]'::jsonb,
  true,
  false,
  false,
  false,
  false,
  'Shadow/watch only. Domestic cup rotation can be noisy; require lineup/goalkeeper and verified market before review.'
)
ON CONFLICT (league_id) DO UPDATE SET
  canonical_name = EXCLUDED.canonical_name,
  display_name = EXCLUDED.display_name,
  confederation = EXCLUDED.confederation,
  region = EXCLUDED.region,
  country = EXCLUDED.country,
  competition_type = EXCLUDED.competition_type,
  tier = EXCLUDED.tier,
  trust_status = EXCLUDED.trust_status,
  trust_score = EXCLUDED.trust_score,
  priority_score = EXCLUDED.priority_score,
  enabled = EXCLUDED.enabled,
  markets_enabled = EXCLUDED.markets_enabled,
  provider_mappings = EXCLUDED.provider_mappings,
  aliases = EXCLUDED.aliases,
  is_domestic = EXCLUDED.is_domestic,
  is_continental = EXCLUDED.is_continental,
  is_global = EXCLUDED.is_global,
  is_friendly = EXCLUDED.is_friendly,
  manual_only = EXCLUDED.manual_only,
  notes = EXCLUDED.notes,
  updated_at = now();
